### ISSUE TITLE
disabling-enabling features

### ISSUE THREAD

**Issue by martiinezz** [int2str/NoSpark#7]
Is there a way to disable features like LCD? I want to fit this code onto ATMEGA8. All I need is pilot generation and basic security like diode check, ground monitoring.

**Comment by int2str** [comment]
No, there is no predefined way to disable features. However, the code is very modular. And simply commenting out the LCD and Keyboard init lines in main.cc will remove that code. I gave it a quick try and that moves the code down to about 15kb, so still not where you need it. I suspect the majority of the code from there is the serial console code. Commenting that out might get you where you need to be, but then you cannot configure the device anymore or collect statistics. 
Which might be ok for your use case, no idea.

**Comment by martiinezz** [comment]
It's really cool - was able to remove all the stuff I don't need and ended up with 6k of hex. It's really cool. Now I need to learn how to add my own modules (like RGB LED support).
